--------------------------------------------------------
--  Fichier créé - mercredi-novembre-03-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VOLS
--------------------------------------------------------

  CREATE TABLE "INES"."VOLS" 
   (	"NUMERO" NUMBER, 
	"DESTINATION" VARCHAR2(20 BYTE), 
	"HORAIRE" TIMESTAMP (6), 
	"SUIVI" VARCHAR2(20 BYTE), 
	"IDENTIFIANT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into INES.VOLS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index NUMERO_VOL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INES"."NUMERO_VOL_PK" ON "INES"."VOLS" ("NUMERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table VOLS
--------------------------------------------------------

  ALTER TABLE "INES"."VOLS" ADD CONSTRAINT "NUMERO_VOL_PK" PRIMARY KEY ("NUMERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INES"."VOLS" MODIFY ("NUMERO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table VOLS
--------------------------------------------------------

  ALTER TABLE "INES"."VOLS" ADD CONSTRAINT "IDENTIFIANT_AVION_FK" FOREIGN KEY ("NUMERO")
	  REFERENCES "INES"."AVION" ("IDENTIFIANT") ENABLE;
