--------------------------------------------------------
--  Fichier créé - mercredi-novembre-03-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VOL
--------------------------------------------------------

  CREATE TABLE "INES"."VOL" 
   (	"NUMERO" NUMBER, 
	"DESTINATION" VARCHAR2(20 BYTE), 
	"HORAIRE" TIMESTAMP (6), 
	"SUIVI" VARCHAR2(20 BYTE), 
	"IDENTIFIANT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVER
--------------------------------------------------------

  CREATE TABLE "INES"."RESERVER" 
   (	"CIN" NUMBER, 
	"NUMERO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GERER4
--------------------------------------------------------

  CREATE TABLE "INES"."GERER4" 
   (	"MATRICULE" NUMBER, 
	"NUMERO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GERER3
--------------------------------------------------------

  CREATE TABLE "INES"."GERER3" 
   (	"MATRICULE" NUMBER, 
	"IDENTIFIANT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GERER2
--------------------------------------------------------

  CREATE TABLE "INES"."GERER2" 
   (	"MATRICULE" NUMBER, 
	"CIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GERER
--------------------------------------------------------

  CREATE TABLE "INES"."GERER" 
   (	"MATRICULE" NUMBER, 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "INES"."EMPLOYE" 
   (	"MATRICULE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DATE_DE_NAISSANCE" DATE, 
	"POSTE" VARCHAR2(20 BYTE), 
	"SALAIRE" FLOAT(126), 
	"EMP_MATRICULE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLACEMENT
--------------------------------------------------------

  CREATE TABLE "INES"."EMPLACEMENT" 
   (	"ID" NUMBER, 
	"LIGNE" NUMBER, 
	"ETAT" VARCHAR2(20 BYTE), 
	"SENS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "INES"."CLIENT" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DATE_DE_NAISSANCE" DATE, 
	"NATIONALITE" VARCHAR2(20 BYTE), 
	"NUMERO_TELEPHONE" NUMBER, 
	"ADRESSE_MAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AVION
--------------------------------------------------------

  CREATE TABLE "INES"."AVION" 
   (	"IDENTIFIANT" NUMBER, 
	"CAPACITE" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE), 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into INES.VOL
SET DEFINE OFF;
REM INSERTING into INES.RESERVER
SET DEFINE OFF;
REM INSERTING into INES.GERER4
SET DEFINE OFF;
REM INSERTING into INES.GERER3
SET DEFINE OFF;
REM INSERTING into INES.GERER2
SET DEFINE OFF;
REM INSERTING into INES.GERER
SET DEFINE OFF;
REM INSERTING into INES.EMPLOYE
SET DEFINE OFF;
REM INSERTING into INES.EMPLACEMENT
SET DEFINE OFF;
REM INSERTING into INES.CLIENT
SET DEFINE OFF;
REM INSERTING into INES.AVION
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index NUMERO_VOL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INES"."NUMERO_VOL_PK" ON "INES"."VOL" ("NUMERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESERVER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INES"."RESERVER_PK" ON "INES"."RESERVER" ("CIN", "NUMERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GERER4_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INES"."GERER4_PK" ON "INES"."GERER4" ("MATRICULE", "NUMERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GERER3_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INES"."GERER3_PK" ON "INES"."GERER3" ("MATRICULE", "IDENTIFIANT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GERER2_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INES"."GERER2_PK" ON "INES"."GERER2" ("MATRICULE", "CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GERER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INES"."GERER_PK" ON "INES"."GERER" ("MATRICULE", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MATRICULE_EMPLOYE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INES"."MATRICULE_EMPLOYE_PK" ON "INES"."EMPLOYE" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ID_EMPLACEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INES"."ID_EMPLACEMENT_PK" ON "INES"."EMPLACEMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INES"."CLIENT_PK" ON "INES"."CLIENT" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDENTIFIANT_AVION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INES"."IDENTIFIANT_AVION_PK" ON "INES"."AVION" ("IDENTIFIANT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table VOL
--------------------------------------------------------

  ALTER TABLE "INES"."VOL" ADD CONSTRAINT "NUMERO_VOL_PK" PRIMARY KEY ("NUMERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INES"."VOL" MODIFY ("NUMERO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVER
--------------------------------------------------------

  ALTER TABLE "INES"."RESERVER" ADD CONSTRAINT "RESERVER_PK" PRIMARY KEY ("CIN", "NUMERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INES"."RESERVER" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "INES"."RESERVER" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GERER4
--------------------------------------------------------

  ALTER TABLE "INES"."GERER4" ADD CONSTRAINT "GERER4_PK" PRIMARY KEY ("MATRICULE", "NUMERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INES"."GERER4" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "INES"."GERER4" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GERER3
--------------------------------------------------------

  ALTER TABLE "INES"."GERER3" ADD CONSTRAINT "GERER3_PK" PRIMARY KEY ("MATRICULE", "IDENTIFIANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INES"."GERER3" MODIFY ("IDENTIFIANT" NOT NULL ENABLE);
  ALTER TABLE "INES"."GERER3" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GERER2
--------------------------------------------------------

  ALTER TABLE "INES"."GERER2" ADD CONSTRAINT "GERER2_PK" PRIMARY KEY ("MATRICULE", "CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INES"."GERER2" MODIFY ("CIN" NOT NULL ENABLE);
  ALTER TABLE "INES"."GERER2" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GERER
--------------------------------------------------------

  ALTER TABLE "INES"."GERER" ADD CONSTRAINT "GERER_PK" PRIMARY KEY ("MATRICULE", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INES"."GERER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "INES"."GERER" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "INES"."EMPLOYE" ADD CONSTRAINT "MATRICULE_EMPLOYE_PK" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INES"."EMPLOYE" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLACEMENT
--------------------------------------------------------

  ALTER TABLE "INES"."EMPLACEMENT" ADD CONSTRAINT "ID_EMPLACEMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INES"."EMPLACEMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "INES"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INES"."CLIENT" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AVION
--------------------------------------------------------

  ALTER TABLE "INES"."AVION" ADD CONSTRAINT "IDENTIFIANT_AVION_PK" PRIMARY KEY ("IDENTIFIANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INES"."AVION" MODIFY ("IDENTIFIANT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table VOL
--------------------------------------------------------

  ALTER TABLE "INES"."VOL" ADD CONSTRAINT "IDENTIFIANT_AVION_FK" FOREIGN KEY ("NUMERO")
	  REFERENCES "INES"."AVION" ("IDENTIFIANT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVER
--------------------------------------------------------

  ALTER TABLE "INES"."RESERVER" ADD CONSTRAINT "CIN_CLIENT_FK2" FOREIGN KEY ("CIN")
	  REFERENCES "INES"."CLIENT" ("CIN") ENABLE;
  ALTER TABLE "INES"."RESERVER" ADD CONSTRAINT "NUMERO_VOL_FK1" FOREIGN KEY ("NUMERO")
	  REFERENCES "INES"."VOL" ("NUMERO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GERER4
--------------------------------------------------------

  ALTER TABLE "INES"."GERER4" ADD CONSTRAINT "MATRICULE_EMPLOYE_FK1" FOREIGN KEY ("MATRICULE")
	  REFERENCES "INES"."EMPLOYE" ("MATRICULE") ENABLE;
  ALTER TABLE "INES"."GERER4" ADD CONSTRAINT "NUMERO_VOL_FK2" FOREIGN KEY ("NUMERO")
	  REFERENCES "INES"."VOL" ("NUMERO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GERER3
--------------------------------------------------------

  ALTER TABLE "INES"."GERER3" ADD CONSTRAINT "IDENTIFIANT_AVION_FK2" FOREIGN KEY ("IDENTIFIANT")
	  REFERENCES "INES"."AVION" ("IDENTIFIANT") ENABLE;
  ALTER TABLE "INES"."GERER3" ADD CONSTRAINT "MATRICULE_EMP_FK1" FOREIGN KEY ("MATRICULE")
	  REFERENCES "INES"."EMPLOYE" ("MATRICULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GERER2
--------------------------------------------------------

  ALTER TABLE "INES"."GERER2" ADD CONSTRAINT "CIN_FK2" FOREIGN KEY ("CIN")
	  REFERENCES "INES"."CLIENT" ("CIN") ENABLE;
  ALTER TABLE "INES"."GERER2" ADD CONSTRAINT "MAATRICULE_FK1" FOREIGN KEY ("MATRICULE")
	  REFERENCES "INES"."EMPLOYE" ("MATRICULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GERER
--------------------------------------------------------

  ALTER TABLE "INES"."GERER" ADD CONSTRAINT "ID_EMPLACEMENT_FK2" FOREIGN KEY ("ID")
	  REFERENCES "INES"."EMPLACEMENT" ("ID") ENABLE;
  ALTER TABLE "INES"."GERER" ADD CONSTRAINT "MATRICULE_EMPL_FK1" FOREIGN KEY ("MATRICULE")
	  REFERENCES "INES"."EMPLOYE" ("MATRICULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "INES"."EMPLOYE" ADD CONSTRAINT "EMP_MATRICULE_FK" FOREIGN KEY ("MATRICULE")
	  REFERENCES "INES"."EMPLOYE" ("MATRICULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AVION
--------------------------------------------------------

  ALTER TABLE "INES"."AVION" ADD CONSTRAINT "ID_EMPLACEMENT_FK" FOREIGN KEY ("ID")
	  REFERENCES "INES"."EMPLACEMENT" ("ID") ENABLE;
--------------------------------------------------------
--  Fichier créé - mercredi-novembre-03-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VOL
--------------------------------------------------------

  CREATE TABLE "system"."VOL" 
   (	"NUMERO" NUMBER, 
	"DESTINATION" VARCHAR2(20 BYTE), 
	"HORAIRE" TIMESTAMP (6), 
	"SUIVI" VARCHAR2(20 BYTE), 
	"IDENTIFIANT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVER
--------------------------------------------------------

  CREATE TABLE "system"."RESERVER" 
   (	"CIN" NUMBER, 
	"NUMERO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GERER4
--------------------------------------------------------

  CREATE TABLE "system"."GERER4" 
   (	"MATRICULE" NUMBER, 
	"NUMERO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GERER3
--------------------------------------------------------

  CREATE TABLE "system"."GERER3" 
   (	"MATRICULE" NUMBER, 
	"IDENTIFIANT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GERER2
--------------------------------------------------------

  CREATE TABLE "system"."GERER2" 
   (	"MATRICULE" NUMBER, 
	"CIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GERER
--------------------------------------------------------

  CREATE TABLE "system"."GERER" 
   (	"MATRICULE" NUMBER, 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "system"."EMPLOYE" 
   (	"MATRICULE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DATE_DE_NAISSANCE" DATE, 
	"POSTE" VARCHAR2(20 BYTE), 
	"SALAIRE" FLOAT(126), 
	"EMP_MATRICULE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLACEMENT
--------------------------------------------------------

  CREATE TABLE "system"."EMPLACEMENT" 
   (	"ID" NUMBER, 
	"LIGNE" NUMBER, 
	"ETAT" VARCHAR2(20 BYTE), 
	"SENS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "system"."CLIENT" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DATE_DE_NAISSANCE" DATE, 
	"NATIONALITE" VARCHAR2(20 BYTE), 
	"NUMERO_TELEPHONE" NUMBER, 
	"ADRESSE_MAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AVION
--------------------------------------------------------

  CREATE TABLE "system"."AVION" 
   (	"IDENTIFIANT" NUMBER, 
	"CAPACITE" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE), 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into system.VOL
SET DEFINE OFF;
REM INSERTING into system.RESERVER
SET DEFINE OFF;
REM INSERTING into system.GERER4
SET DEFINE OFF;
REM INSERTING into system.GERER3
SET DEFINE OFF;
REM INSERTING into system.GERER2
SET DEFINE OFF;
REM INSERTING into system.GERER
SET DEFINE OFF;
REM INSERTING into system.EMPLOYE
SET DEFINE OFF;
REM INSERTING into system.EMPLACEMENT
SET DEFINE OFF;
REM INSERTING into system.CLIENT
SET DEFINE OFF;
REM INSERTING into system.AVION
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index NUMERO_VOL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "system"."NUMERO_VOL_PK" ON "system"."VOL" ("NUMERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESERVER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "system"."RESERVER_PK" ON "system"."RESERVER" ("CIN", "NUMERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GERER4_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "system"."GERER4_PK" ON "system"."GERER4" ("MATRICULE", "NUMERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GERER3_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "system"."GERER3_PK" ON "system"."GERER3" ("MATRICULE", "IDENTIFIANT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GERER2_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "system"."GERER2_PK" ON "system"."GERER2" ("MATRICULE", "CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GERER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "system"."GERER_PK" ON "system"."GERER" ("MATRICULE", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MATRICULE_EMPLOYE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "system"."MATRICULE_EMPLOYE_PK" ON "system"."EMPLOYE" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ID_EMPLACEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "system"."ID_EMPLACEMENT_PK" ON "system"."EMPLACEMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "system"."CLIENT_PK" ON "system"."CLIENT" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDENTIFIANT_AVION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "system"."IDENTIFIANT_AVION_PK" ON "system"."AVION" ("IDENTIFIANT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table VOL
--------------------------------------------------------

  ALTER TABLE "system"."VOL" ADD CONSTRAINT "NUMERO_VOL_PK" PRIMARY KEY ("NUMERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "system"."VOL" MODIFY ("NUMERO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVER
--------------------------------------------------------

  ALTER TABLE "system"."RESERVER" ADD CONSTRAINT "RESERVER_PK" PRIMARY KEY ("CIN", "NUMERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "system"."RESERVER" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "system"."RESERVER" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GERER4
--------------------------------------------------------

  ALTER TABLE "system"."GERER4" ADD CONSTRAINT "GERER4_PK" PRIMARY KEY ("MATRICULE", "NUMERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "system"."GERER4" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "system"."GERER4" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GERER3
--------------------------------------------------------

  ALTER TABLE "system"."GERER3" ADD CONSTRAINT "GERER3_PK" PRIMARY KEY ("MATRICULE", "IDENTIFIANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "system"."GERER3" MODIFY ("IDENTIFIANT" NOT NULL ENABLE);
  ALTER TABLE "system"."GERER3" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GERER2
--------------------------------------------------------

  ALTER TABLE "system"."GERER2" ADD CONSTRAINT "GERER2_PK" PRIMARY KEY ("MATRICULE", "CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "system"."GERER2" MODIFY ("CIN" NOT NULL ENABLE);
  ALTER TABLE "system"."GERER2" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GERER
--------------------------------------------------------

  ALTER TABLE "system"."GERER" ADD CONSTRAINT "GERER_PK" PRIMARY KEY ("MATRICULE", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "system"."GERER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "system"."GERER" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "system"."EMPLOYE" ADD CONSTRAINT "MATRICULE_EMPLOYE_PK" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "system"."EMPLOYE" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLACEMENT
--------------------------------------------------------

  ALTER TABLE "system"."EMPLACEMENT" ADD CONSTRAINT "ID_EMPLACEMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "system"."EMPLACEMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "system"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "system"."CLIENT" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AVION
--------------------------------------------------------

  ALTER TABLE "system"."AVION" ADD CONSTRAINT "IDENTIFIANT_AVION_PK" PRIMARY KEY ("IDENTIFIANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "system"."AVION" MODIFY ("IDENTIFIANT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table VOL
--------------------------------------------------------

  ALTER TABLE "system"."VOL" ADD CONSTRAINT "IDENTIFIANT_AVION_FK" FOREIGN KEY ("NUMERO")
	  REFERENCES "system"."AVION" ("IDENTIFIANT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVER
--------------------------------------------------------

  ALTER TABLE "system"."RESERVER" ADD CONSTRAINT "CIN_CLIENT_FK2" FOREIGN KEY ("CIN")
	  REFERENCES "system"."CLIENT" ("CIN") ENABLE;
  ALTER TABLE "system"."RESERVER" ADD CONSTRAINT "NUMERO_VOL_FK1" FOREIGN KEY ("NUMERO")
	  REFERENCES "system"."VOL" ("NUMERO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GERER4
--------------------------------------------------------

  ALTER TABLE "system"."GERER4" ADD CONSTRAINT "MATRICULE_EMPLOYE_FK1" FOREIGN KEY ("MATRICULE")
	  REFERENCES "system"."EMPLOYE" ("MATRICULE") ENABLE;
  ALTER TABLE "system"."GERER4" ADD CONSTRAINT "NUMERO_VOL_FK2" FOREIGN KEY ("NUMERO")
	  REFERENCES "system"."VOL" ("NUMERO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GERER3
--------------------------------------------------------

  ALTER TABLE "system"."GERER3" ADD CONSTRAINT "IDENTIFIANT_AVION_FK2" FOREIGN KEY ("IDENTIFIANT")
	  REFERENCES "system"."AVION" ("IDENTIFIANT") ENABLE;
  ALTER TABLE "system"."GERER3" ADD CONSTRAINT "MATRICULE_EMP_FK1" FOREIGN KEY ("MATRICULE")
	  REFERENCES "system"."EMPLOYE" ("MATRICULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GERER2
--------------------------------------------------------

  ALTER TABLE "system"."GERER2" ADD CONSTRAINT "CIN_FK2" FOREIGN KEY ("CIN")
	  REFERENCES "system"."CLIENT" ("CIN") ENABLE;
  ALTER TABLE "system"."GERER2" ADD CONSTRAINT "MAATRICULE_FK1" FOREIGN KEY ("MATRICULE")
	  REFERENCES "system"."EMPLOYE" ("MATRICULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GERER
--------------------------------------------------------

  ALTER TABLE "system"."GERER" ADD CONSTRAINT "ID_EMPLACEMENT_FK2" FOREIGN KEY ("ID")
	  REFERENCES "system"."EMPLACEMENT" ("ID") ENABLE;
  ALTER TABLE "system"."GERER" ADD CONSTRAINT "MATRICULE_EMPL_FK1" FOREIGN KEY ("MATRICULE")
	  REFERENCES "system"."EMPLOYE" ("MATRICULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "system"."EMPLOYE" ADD CONSTRAINT "EMP_MATRICULE_FK" FOREIGN KEY ("MATRICULE")
	  REFERENCES "system"."EMPLOYE" ("MATRICULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AVION
--------------------------------------------------------

  ALTER TABLE "system"."AVION" ADD CONSTRAINT "ID_EMPLACEMENT_FK" FOREIGN KEY ("ID")
	  REFERENCES "system"."EMPLACEMENT" ("ID") ENABLE;
